### ISSUE TITLE
Not work on local

### ISSUE THREAD

**Issue by neicv** [SPQRInc/pagekit-backups#1]
Hi!
I use localhost on OpenServer

Pagekit Version | 1.0.13
Web Server | Apache
User Agent | Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
PHP 7.04
MySql 5.5.48

Settings - Use Mysqldump

i have "finished" status, but no any zip or etc files can`t be find on local store.
(some have in tmp dir:
files.zip - not empty, but not full contetn (litl files ...)
database.sql - 0 bytes size)
thanks you in advance!

**Comment by ahoiroman** [comment]
Hi and thank you for your report.

First of all: Please enable debug mode.

If you check out all network activity from the browser after you started the backup, you should see a lot happening there.

Please run your backup and watch out for results, that have not status `200`. 

![bildschirmfoto 2017-10-06 um 13 57 03](https://user-images.githubusercontent.com/23051150/31276940-c4a0d164-aa9e-11e7-9a24-f02994e199c7.png)


Once you found the problem, please check the response and post it here.

I think the error will be shown on archiveDatabase.

![bildschirmfoto 2017-10-06 um 14 02 41](https://user-images.githubusercontent.com/23051150/31277017-16a563da-aa9f-11e7-96ba-e4f787539fe3.png)
![bildschirmfoto 2017-10-06 um 14 02 46](https://user-images.githubusercontent.com/23051150/31277018-16c32cc6-aa9f-11e7-808f-8cf51ae7cd76.png)

**Comment by ahoiroman** [comment]
Closed as there are no further information provided. Please reopen, if necessary.
